---
title: "project"
format: html
editor: visual
---

```{r}
#| include: false
library(bayesrules)
library(tidyverse)
library(rstan)
library(rstanarm)
library(bayesplot)
library(tidybayes)
library(janitor)
library(broom.mixed)
```

## Week 8 Tasks

```{r}
dataset <- read.csv("../data/data.csv")
```

### Clean the dataset

```{r}
data <- dataset |>
  select(
    gallstone = Gallstone.Status,
    gender = Gender,
    age = Age,
    bfr = Total.Body.Fat.Ratio..TBFR.....,
    bmi = Body.Mass.Index..BMI.,
    glucose = Glucose,
    comorbid = Comorbidity,
    height = Height,
    weight = Weight,
    tbw = Total.Body.Water..TBW.,
    ecw = Extracellular.Water..ECW.,
    icw = Intracellular.Water..ICW.,
    ecftbw = Extracellular.Fluid.Total.Body.Water..ECF.TBW.,
    tbfr = Total.Body.Fat.Ratio..TBFR.....,
    lean_mass = Lean.Mass..LM.....,
    bpc = Body.Protein.Content..Protein.....,
    vfr = Visceral.Fat.Rating..VFR.,
    bone_mass = Bone.Mass..BM.,
    musc_mass = Muscle.Mass..MM.,
    obesity = Obesity....,
    tfc = Total.Fat.Content..TFC.,
    vfa = Visceral.Fat.Area..VFA.,
    vma = Visceral.Muscle.Area..VMA...Kg.,
    hfa = Hepatic.Fat.Accumulation..HFA.,
    tc = Total.Cholesterol..TC.,
    ldl = Low.Density.Lipoprotein..LDL.,
    hdl = High.Density.Lipoprotein..HDL.,
    trigly = Triglyceride,
    alt = Alanin.Aminotransferaz..ALT.,
    alp = Alkaline.Phosphatase..ALP.,
    creat = Creatinine,
    gfr = Glomerular.Filtration.Rate..GFR.,
    crp = C.Reactive.Protein..CRP.,
    hgb = Hemoglobin..HGB.,
    vita_d = Vitamin.D
  ) |>
  mutate(comorbid = ifelse(comorbid == 0, 0, 1),
         gallstone = ifelse(gallstone == 0, 1, 0))
head(data)
```

### EDA

```{r}
prior_model <- stan_glm(
  gallstone ~ bone_mass + gender + age + icw + hfa + crp + hgb + vita_d,
  data = data,
  family = binomial(link = "logit"),
  prior_intercept = normal(location = qlogis(0.0605), scale = abs(qlogis(0.065) - qlogis(0.056)) / 4, autoscale = F),
  prior = normal(location = 0, scale = 2.5, autoscale = T),
  chains = 4, iter = 5000*2, seed = 84735,
  prior_PD = T, refresh = F, cores = 16
)
```

```{r}
neff_ratio(prior_model)
rhat(prior_model)
mcmc_trace(prior_model)
mcmc_dens_overlay(prior_model)
mcmc_acf(prior_model)
```

```{r}
set.seed(84735)
data |>
  add_linpred_draws(prior_model, ndraws = 1000) |>
  ggplot(aes(x = gender, y = gallstone)) +
    geom_line(aes(y = .linpred, group = .draw), size = 0.10, alpha = 0.30)
```

```{r}
set.seed(84735)
data |>
  add_epred_draws(prior_model, ndraws = 1000) |>
  group_by(.draw) |>
  ggplot(aes(x = .epred)) +
    geom_histogram(color = "white", binwidth = 0.05, boundary = 0)
```

```{r}
posterior_model <- update(prior_model, prior_PD = F)
```

```{r}
neff_ratio(posterior_model)
rhat(posterior_model)
mcmc_trace(posterior_model)
mcmc_dens_overlay(posterior_model)
mcmc_acf(posterior_model)
```

```{r}
set.seed(84735)
data |>
  add_linpred_draws(posterior_model, ndraws = 1000) |>
  ggplot(aes(x = gender, y = gallstone)) +
    geom_line(aes(y = .linpred, group = .draw), size = 0.10, alpha = 0.30) +
    labs(y = "prob of gallstone")
```

```{r}
# log(odds)
posterior_interval(posterior_model, prob = 0.95)
```

```{r}
# odds
exp(posterior_interval(posterior_model, prob = 0.95))
```

```{r}
proportion_gallstone <- function(x){mean(x == 1)}
pp_check(posterior_model, nreps = 1000,
         plotfun = "stat", stat = "proportion_gallstone") + 
  xlab("probability of gallstone")
```

```{r}
set.seed(84735)
range <- seq(from = 0.05, to = 0.95, by = 0.01)
for (i in range) {
  print(classification_summary(model = posterior_model, data = data, cutoff = i)$accuracy_rates)
}
```

```{r}
set.seed(84735)
cv_accuracy <- classification_summary_cv(
  model = posterior_model, data = data, cutoff = 0.395, k = 10)
```

```{r}
cv_accuracy
```

```{r}
# log(odds)
tidy(posterior_model, effects = "fixed", conf.int = TRUE, conf.level = 0.95)
```

```{r}
pp_check(posterior_model, nreps = 100)
```

